// Units Constants
export const GET_UNITS_REQUEST = "GET_UNITS_REQUEST";
export const GET_UNITS_SUCCESS = "GET_UNITS_SUCCESS";
export const GET_UNITS_FAILURE = "GET_UNITS_FAILURE";

//Unit Constants
export const GET_UNIT_REQUEST = "GET_UNIT_REQUEST";
export const GET_UNIT_SUCCESS = "GET_UNIT_SUCCESS";
export const GET_UNIT_FAILURE = "GET_UNIT_FAILURE";
